title: SURVITAC
description: SURVITAC Website that looks like JSON
baseurl: ""
url: https://survitac.jp

# theme: hacked-jekyll
remote_theme: piazzai/hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never

lowercase: false
  